In [1]:
import pandas as pd

df = pd.read_csv("../data/samplesuperstore.csv")
df.shape

(9993, 13)

In [2]:
step1 = df[df["Segment"] == "Consumer"]
print(f"[MANUAL] after filter: shape={step1.shape}")
step1.head(3)

[MANUAL] after filter: shape=(5190, 13)

,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub-Category,Sales,Quantity,Discount,Profit
0,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,261.9600,2,0.00,41.9136
1,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,731.9400,3,0.00,219.5820
3,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,957.5775,5,0.45,-383.0310

In [3]:
step2 = step1.groupby("Sub-Category")["Profit"].mean().reset_index()
step2

   Sub-Category      Profit
0   Accessories   50.823339
1    Appliances   28.432017
2           Art    8.070797
3       Binders   23.071278
4     Bookcases  -33.859834
5        Chairs   40.228972
6       Copiers  688.106017
7     Envelopes   25.305524
8     Fasteners    5.059656
9   Furnishings   16.031220
10       Labels   16.275071
11     Machines   37.562488
12        Paper   22.416513
13       Phones   52.853913
14      Storage   15.787112
15     Supplies  -16.575513
16       Tables  -61.182628

In [4]:
step1 = df[df["Segment"] == "Consumer"]
print(f"[MANUAL] after filter: shape={step1.shape}")

step2 = step1.groupby("Sub-Category")["Profit"].mean().reset_index()
step2

[MANUAL] after filter: shape=(5190, 13)

   Sub-Category      Profit
0   Accessories   50.823339
1    Appliances   28.432017
2           Art    8.070797
3       Binders   23.071278
4     Bookcases  -33.859834
5        Chairs   40.228972
6       Copiers  688.106017
7     Envelopes   25.305524
8     Fasteners    5.059656
9   Furnishings   16.031220
10       Labels   16.275071
11     Machines   37.562488
12        Paper   22.416513
13       Phones   52.853913
14      Storage   15.787112
15     Supplies  -16.575513
16       Tables  -61.182628

In [5]:
[
  {"operation": "filter", "filter_column": "Category", "filter_value": "Technology"},
  {"operation": "describe", "value_column": "Profit"}
]

[{'operation': 'filter',
  'filter_column': 'Category',
  'filter_value': 'Technology'},
 {'operation': 'describe', 'value_column': 'Profit'}]

In [6]:
tech = df[df["Category"] == "Technology"]
print(tech.shape)
tech["Profit"].describe()

(1847, 13)

count    1847.000000
mean       78.752002
std       428.816633
min     -6599.978000
25%         5.203650
50%        25.018200
75%        74.894600
max      8399.976000
Name: Profit, dtype: float64